### ISSUE TITLE
a junk drawer of things to internalize (2015 edition)

### ISSUE THREAD

**Issue by rick** [rick/life#6]
![](http://www.jonathanrosenbaum.net/wp-content/uploads/2009/03/coffee-and-cigarettes.jpg)

**To review media that I've already internalized this year, check out: [2015 consumed media](https://github.com/rick/life/issues/7)**

**legend**: :money_with_wings: - already own this

#### Books
 - **in progress** (I clearly have a problem with commitment):
   - [ ] :money_with_wings: **book club**: [7 concurrency models in 7 weeks](http://www.amazon.com/Seven-Concurrency-Models-Weeks-Programmers/dp/1937785653/)
   - [ ] :money_with_wings: [When the Body Says No](http://www.amazon.com/When-Body-Says-Stress-Disease-Connection/dp/0470923350/)
   - [ ] :money_with_wings: [In an Unspoken Voice](http://www.amazon.com/Unspoken-Voice-Releases-Restores-Goodness/dp/1556439431/)
   - [ ] :money_with_wings: [The Language of Emotions](http://www.amazon.com/Language-Emotions-What-Feelings-Trying/dp/1591797691/)
   - [ ] :money_with_wings: [Last Night a DJ saved my life](http://www.amazon.com/Last-Night-DJ-Saved-Life/dp/0802146104/)
   - [ ] :money_with_wings: [Lies My Teacher Told Me](http://www.amazon.com/Lies-My-Teacher-Told-Everything/dp/0743296281/)
   - [ ] :money_with_wings: [Wake up to your life](http://www.amazon.com/Wake-Your-Life-Discovering-Attention/dp/0062516817/) (re-read)
   - [ ] :money_with_wings: [The Process of Creating Life: Nature of Order, Book 2](http://www.amazon.com/Process-Creating-Life-Building-Universe/dp/0972652922/)
   - [ ] :money_with_wings: [The Toyota Way](http://www.amazon.com/Toyota-Way-Management-Principles-Manufacturer/dp/0071392319/)
   - [ ] :money_with_wings: [Discover Meteor](https://www.discovermeteor.com/)
   - [ ] :money_with_wings: [Urban Tantra](http://www.amazon.com/Urban-Tantra-Sacred-Twenty-First-Century/dp/1587612909/)
   - [ ] :money_with_wings: [Idealized Design](http://www.amazon.com/Idealized-Design-Dissolve-Tomorrows-paperback/dp/0137071116/)
   - [ ] :money_with_wings: [Peopleware](http://www.amazon.com/Peopleware-Productive-Projects-Teams-3rd/dp/0321934113/)
   - [ ] :money_with_wings: [Predictably Irrational](http://www.amazon.com/Predictably-Irrational-Revised-Expanded-Decisions/dp/0061353248/)
   - [ ] :money_with_wings: [Agile Retrospectives](http://www.amazon.com/Agile-Retrospectives-Making-Teams-Great/dp/0977616649/)
   - [ ] :money_with_wings: [The Asian Journal of Thomas Merton](http://www.amazon.com/Asian-Journal-Thomas-Merton-Directions/dp/0811205703/)

 - **parenting**:
   - [ ] [free range kids](http://www.amazon.com/Free-Range-Giving-Children-Freedom-Without/dp/0470471948/)

 - **meditation**:
   - [ ] :money_with_wings: [The Collected Works of Chogyam Trungpa: Volume 3](http://www.amazon.com/Collected-Works-Chogyam-Trungpa-Materialism/dp/1590300270/)
   - [ ] [Dzogchen: The Heart Essence of the Great Perfection; by HH the Dalai Lama](http://www.amazon.com/Dzogchen-Heart-Essence-Great-Perfection/dp/1559392193/)
   - [ ] [The practice of dzogchen : Longchen rabjam's writings on the great perfection](http://www.amazon.com/The-Practice-Dzogchen-Perfection-Buddhayana/dp/155939434X)
   - [ ] ["A path with a Heart" by Jack Kornfield](http://www.amazon.com/Path-Heart-Through-Promises-Spiritual/dp/0553372114/)
   - [ ] [opening the hand of thought, foundations of zen buddhist practice](http://www.amazon.com/Opening-Hand-Thought-Foundations-Buddhist/dp/0861713575)
   - [ ] ["Lovingkindness: The Revolutionary Art of Happiness" by Sharon Salzberg ](http://www.amazon.com/Lovingkindness-Revolutionary-Happiness-Shambhala-Classics/dp/157062903X/ref=asap_bc?ie=UTF8)
   - [ ] ["Mindfulness for Everyday Living" by Christopher Titmuss](http://www.amazon.com/Mindfulness-Everyday-Living-Christopher-Titmuss/dp/0764122606)
   - [ ] :money_with_wings: Chogyam Trungpa Rinpoche audio: http://www.chronicleproject.com/CTRlibrary/index_CTRlibrary.html
 - [ ] :money_with_wings: [How music works](http://www.amazon.com/How-Music-Works-David-Byrne/dp/1938073533/)
 - [x] ~~:money_with_wings: [Too big to know](http://www.amazon.com/Too-Big-Know-Rethinking-Everywhere/dp/0465085962)~~ (decided to let this go)
 - [ ] :money_with_wings: [How to be an adult](http://www.amazon.com/How-Adult-Psychological-Spiritual-Integration/dp/0809132230/)
 - [ ] :money_with_wings: [What Did You Say?](http://www.amazon.com/What-Did-You-Say-Receiving/dp/0965043002/)
 - [ ] :money_with_wings: [Release It!](http://www.amazon.com/Release-Production-Ready-Software-Pragmatic-Programmers/dp/0978739213/)
 - [ ] :money_with_wings: [The Hit](http://www.amazon.com/Hit-Will-Robie-David-Baldacci/dp/1455521302/)
 - [ ] :money_with_wings: [Homage to Catalonia](http://www.amazon.com/Homage-Catalonia-George-Orwell/dp/0156421178/)
 - [ ] :money_with_wings: [Cohousing](http://www.amazon.com/Cohousing-Contemporary-Approach-Housing-Ourselves/dp/0898155398/)
 - [ ] :money_with_wings: [The failure of modern architecture](http://www.amazon.com/Failure-Modern-Architecture-C-Brent-Brolin/dp/0289707536/)
 - [ ] ["Your code as a crime scene"](https://pragprog.com/book/atcrime/your-code-as-a-crime-scene) (pragprog)
 - [ ] ["Bloodlands: Europe Between Hitler and Stalin"](http://www.amazon.com/Bloodlands-Europe-Between-Hitler-Stalin/dp/0465031471/) 
 - [ ] ["Fluent Forever"](http://www.amazon.com/Fluent-Forever-Learn-Language-Forget/dp/0385348118/)
 - [ ] ["Be prepared: a practical handbook for new dads"](http://www.amazon.com/Be-Prepared-Practical-Handbook-Dads/dp/0743251547)
 - [ ] ["Good Strategy Bad Strategy: The Difference and Why It Matters"](http://www.amazon.com/Good-Strategy-Bad-Difference-Matters/dp/0307886239), via jbarnette
 - [ ] ["The Tender Bar"](http://www.amazon.com/The-Tender-Bar-A-Memoir/dp/0786888768) via al bellos
 - [ ] ["The Myth of the Spoiled Child"](http://www.amazon.com/The-Myth-Spoiled-Child-Conventional/dp/0738217247) 
 - [ ] [Antifragile](http://www.amazon.com/Antifragile-Things-That-Disorder-Incerto/dp/0812979680)
 - [ ] [Super Sad True Love Story](http://www.amazon.com/Super-Sad-True-Love-Story/dp/0812977866)
 - [ ] ["The Circle" by Dave Eggers](http://www.amazon.com/Circle-Dave-Eggers/dp/0345807294/)
 - [ ] ["Addiction by Design: Machine Gambling in Las Vegas"](http://www.amazon.com/Addiction-Design-Machine-Gambling-Vegas/dp/0691160880/)
 - [ ] [In search of certainty](http://markburgess.org/certainty.html)
 - [ ] [Dynamic Hedging](http://www.amazon.com/Dynamic-Hedging-Managing-Vanilla-Options/dp/0471152803) (h/t @norbert -- "For more background see [Options, Futures, and Other Derivatives (9th Edition)](http://www.amazon.com/Options-Futures-Other-Derivatives-Edition/dp/0133456315). /cc @ptegelaar")
 - [ ] [Scalzi - Old Man's War](http://en.wikipedia.org/wiki/Old_Man%27s_War)
 - [ ] [The Dirt (Mötley Crüe)](http://www.amazon.com/The-Dirt-Confessions-Worlds-Notorious/dp/0060989157)

#### Movies / TV ( :movie_camera: :tv: )

 - [x] :money_with_wings: [Predestination](http://en.wikipedia.org/wiki/Predestination_%28film%29) - h/t @vinbarnes
 - [ ] :money_with_wings: [Moon](http://en.wikipedia.org/wiki/Moon_%28film%29) - h/t @vinbarnes
 - [ ] [Gone Girl](http://en.wikipedia.org/wiki/Gone_Girl_%28film%29)
 - [x] :money_with_wings: [Ai Wei Wei: The Fake Case](http://thefakecase.com/)
 - [ ] :money_with_wings: continue watching Ken Burn's "Jazz" documentary
 - [ ] :money_with_wings: [Chappaqua](http://www.imdb.com/title/tt0059025/) (via the soundtrack I already have)
 - [ ] :money_with_wings: that Pavement DVD (personal collection)
 - [ ] :money_with_wings: that "Growing a Beard" DVD (personal collection)
 - [ ] Michael Palin's "The Himalayas" series
 - [ ] ["Mind of a Chef"](http://en.wikipedia.org/wiki/The_Mind_of_a_Chef) (netflix) 
 - [ ] [Festival Express](http://en.wikipedia.org/wiki/Festival_Express)
 - [x] "patton oswald starwars filibuster parks & rec" (comedy bit)
 - [x] "patton oswald amazon rolling joint (comedy bit)
 - [ ] http://www.history.com/shows/the-curse-of-oak-island
 - [ ] "council of ricks" rick & morty episode
 - [ ] [9000 needles](http://www.imdb.com/title/tt1489881/)
 - [ ] ["Going Deep with David Rees"](http://en.wikipedia.org/wiki/Going_Deep_with_David_Rees)
 - [ ] [Black Mirror](http://en.wikipedia.org/wiki/Black_Mirror_%28TV_series%29)
 - [ ] ["I'm not there"](http://en.wikipedia.org/wiki/I%27m_Not_There) (re: bob dylan), via The RIMBoy
 - [ ] [The Source Family](http://www.netflix.com/WiMovie/70234699?trkid=13462100) via wilkes
 - [ ] [Birdman](http://en.wikipedia.org/wiki/Birdman_%28film%29)
 - [ ] [Imitation Game](http://en.wikipedia.org/wiki/The_Imitation_Game) - it's got Benjamin   Cinderblock playing Alan Turing, so it's gotta be good

#### Music

 - [ ] :money_with_wings: http://www.reverbnation.com/thelovesbandNY -- my friend Nicole Clifton's band
 - [ ] :money_with_wings: ["Home"](http://www.rdio.com/artist/Home/), via nathan vasquez
 - [ ] [Loose Fur](http://en.wikipedia.org/wiki/Loose_Fur) (Jeff Tweedy, etc.)
 - [ ] Mr. Oizo (via `The Code Bass Room`)
 - [ ] Phoenix: Wolfgang Amadeus unplugges (via Wilkes)
 - [ ] [Flying Lotus: You're Dead](http://flying-lotus.com/youre-dead/)
 - [ ] [The Beautiful Girls](http://en.wikipedia.org/wiki/The_Beautiful_Girls)
 - [ ] [Shabazz Palaces](http://en.wikipedia.org/wiki/Shabazz_Palaces)
 - [ ] :money_with_wings: watch some "tiny desk concerts": http://www.npr.org/series/tiny-desk-concerts/
 - via Ryan @ Stone Fox:
   - [ ] [tuning circuits - no compassion](http://www.discogs.com/Tuning-Circuits-No-Compassion/release/3450995)
   - [ ] [vasilisk](http://www.discogs.com/artist/80713-Vasilisk)
   - [ ] [chrome](http://www.discogs.com/artist/189293-Chrome-8)
   - [ ] http://www.adampopemusic.com/
   - [ ] http://artmeetsscience.co.uk/tapes/
 - [ ] [Shotgun Willie](http://en.wikipedia.org/wiki/Shotgun_Willie) - pretty sure I've heard this, but need to really sit down with it again
 - [ ] [Jimmy Smith - Root Down](http://en.wikipedia.org/wiki/Root_Down_(album)) - and presumably some other finery

   
#### Online

 - [ ] code presentation: "code as a crime scene": http://vimeo.com/78895777
 - [ ] https://www.youtube.com/watch?v=IxW_D79WPZI - atmos @ re:invent
 - [ ] https://www.youtube.com/watch?v=cGHOjGtsnFg - defunkt @ re:invent
 - [ ] talks from CCC security conference: https://events.ccc.de/congress/2014/Fahrplan/speakers.html
 - [ ] http://ericleads.com/2014/02/prototypal-inheritance-with-stamps/
 - [ ] security book: https://www.cs.auckland.ac.nz/~pgut001/pubs/book.pdf
 - [ ] more shit about tiny houses: http://www.relaxshacks.blogspot.com/
 - [ ] read more: http://sysadvent.blogspot.com/2014/12/day-4-introduction-to-kafka.html
 - [ ] watch more clojureconj videos: https://www.youtube.com/watch?v=4-oyZpLRQ20&index=3&list=PLZdCLR02grLoc322bYirANEso3mmzvCiI
 - [ ] gareth rushgrove video: https://www.youtube.com/watch?v=-47jBdJ1yf0&feature=youtu.be

#### Getting out

 - [ ] music: nashville jazz workshop "x on 2 and 4" monthly
 - [ ] grab some North Mississippi Hill Country Picnic tickets: https://www.eventbrite.com/e/2015-north-mississippi-hill-country-picnic-tickets-14028129513 / cc @vinbarnes

#### WTF

 - [ ] http://rockathonrecords.com/books.html (bob pollard collage books)
 - cooking:
   - [ ] parathas: http://tesathome.com/2011/02/02/kerala-paratha/
   - [ ]  http://nishamadhulika.com/en/648-kerala-parotta-recipe-kerala-paratha.html

**Comment by rick** [comment]
https://events.ccc.de/congress/2014/Fahrplan/speakers.html

**Comment by rick** [comment]
the myth of the spoiled child: http://www.amazon.com/The-Myth-Spoiled-Child-Conventional/dp/0738217247

**Comment by rick** [comment]
more on tiny houses: http://www.relaxshacks.blogspot.com/

**Comment by rick** [comment]
movie: "I'm not there" (bob dylan stuff; via RIMBoy)

**Comment by rick** [comment]
(via: https://medium.com/@hansdezwart/ai-weiwei-is-living-in-our-future-474e5dd15e4f)

book: anti-fragile
movie: ai weiwei: the fake case
book: 'Super Sad True Love Story’, by Gary Shteyngart 
book: the circle by dave eggers
book: addiction by design

**Comment by atmos** [comment]
> movie: "I'm not there" (bob dylan stuff; via RIMBoy)

I was gonna unsubscribe from this issue and then saw some interesting stuff in the list so I'm gonna stay subscribed.

Happy new year @rick

**Comment by rick** [comment]
happy new year man!  I moved this from a private issue to a public one and didn't think about the fact I suddenly cc'd people. My bad!  Enjoy whatever nonsense you can find here.  :bow:

**Comment by rick** [comment]
Finally cleaned up and consolidated this into the header. Comments are here to add suggestions, etc., which I'll consolidate later.  Cheers.  :beers:

**Comment by rick** [comment]
[In search of certainty](http://markburgess.org/certainty.html)

**Comment by norbert** [comment]
@rick yes to your latest comment.

**Comment by rick** [comment]
> @rick yes to your latest comment.

haha -- yeah, you were probably involved in the conversation I was reading where that came up.  :+1:

**Comment by rick** [comment]
:book: for consideration (h/t norbert): [Dynamic Hedging](http://www.amazon.com/Dynamic-Hedging-Managing-Vanilla-Options/dp/0471152803)

**Comment by norbert** [comment]
For more background see [Options, Futures, and Other Derivatives (9th Edition)](http://www.amazon.com/Options-Futures-Other-Derivatives-Edition/dp/0133456315). /cc @ptegelaar

**Comment by rick** [comment]
:book: - [ ] [Scalzi - Old Man's War](http://en.wikipedia.org/wiki/Old_Man%27s_War)

**Comment by vinbarnes** [comment]
> Scalzi - Old Man's War

:+1:

**Comment by rick** [comment]
- :movie_camera: [Predestination](http://en.wikipedia.org/wiki/Predestination_%28film%29)
 - :movie_camera: [Moon](http://en.wikipedia.org/wiki/Moon_%28film%29)

h/t @vinbarnes

**Comment by rick** [comment]
- h/t the @rimboy:
  - [ ] :musical_note: [Shotgun Willie](http://en.wikipedia.org/wiki/Shotgun_Willie) - pretty sure I've heard this, but need to really sit down with it again
  - [ ] :musical_note: [Jimmy Smith - Root Down](http://en.wikipedia.org/wiki/Root_Down_%28album%29) - and presumably some other finery
  - [ ] :book: [The Dirt (Mötley Crüe)](http://www.amazon.com/The-Dirt-Confessions-Worlds-Notorious/dp/0060989157)
  - [ ] :movie_camera: [Birdman](http://en.wikipedia.org/wiki/Birdman_%28film%29)
- [ ] :movie_camera: [Imitation Game](http://en.wikipedia.org/wiki/The_Imitation_Game) - it's got Benjamin   Cinderblock playing Alan Turing, so it's gotta be good

**Comment by rick** [comment]
via @vinbarnes:
- [ ] :movie_camera: [Gone Girl](http://en.wikipedia.org/wiki/Gone_Girl_%28film%29)

**Comment by rimboy** [comment]
Jimmy Smith: Throw in "Finest In Jazz" and "Stay Loose"

Willie:  Shotgun has some solid cuts.  Throw in Stardust for good measure.

The Dirt is a quick, fucked up, read.

Cannot say enough good things about Birdman.

Have to check out Imitation Game.  Was telling someone the story the other
day about being at the WWII codebreaker lecture in Stephenson when the guy
dropped science on what the British govt did to Turing after the war and
how " it never needs to happen again"

Sean

**Comment by rick** [comment]
![](http://bsupulse.com/files/2011/10/Them_Crooked_Vultures_v2_by_autoriot.jpg)
- [ ] :musical_note: [Them Crooked Vultures](http://en.wikipedia.org/wiki/Them_Crooked_Vultures) - the John Paul Jones, Dave Grohl, etc., jawn

**Comment by rimboy** [comment]
Oh shit, forgot about that conversation.

You might also want to throw on that list "All Them Witches" a local
psychadelic rock band.  Good good grooves.  Patrick rocked them one night
at 12S Taproom and it was nice.

**Comment by rick** [comment]
> Oh shit, forgot about that conversation.

Which is why I've gotten in the habit of drunkenly emailing myself things so I can remember them -- no way I would've remembered that had I not had an email about it in my inbox.  On a good night there'll be half a dozen emails of stuff to think about the next day. :metal:

**Comment by rimboy** [comment]
that bartender knew me, but cannot recall meeting him.  He's fucking solid
though, always a good problem to have.  I should start carrying around the
notepad again...

**Comment by vinbarnes** [comment]
> that bartender knew me, but cannot recall meeting him

:sparkles:

**Comment by rick** [comment]
re: cooking:

http://en.wikipedia.org/wiki/Auguste_Escoffier
http://www.amazon.com/Ratio-Simple-Behind-Everyday-Cooking/dp/1416571728
http://www.amazon.co.uk/Modern-Cooks-Handbook-Lynda-Brown/dp/0718138155

**Comment by norbert** [comment]
Keep [Mastering the Art of French Cooking](https://en.wikipedia.org/wiki/Mastering_the_Art_of_French_Cooking) by your side while you go through Escoffier for comparison. My preferred reference for many traditional components (espagnole and so on) is [The French Laundry Cookbook](http://www.amazon.com/French-Laundry-Cookbook-Thomas-Keller/dp/1579651267). Finally you might also be interested in Heston Blumenthal's [In Search of Perfection](http://www.amazon.com/In-Search-Perfection-Heston-Blumenthal/dp/0747584095).

**Comment by rick** [comment]
- [ ] :musical_note: [Bombay 2: Electric Vindaloo](http://www.amazon.com/Bombay-Hard-Way-Vol-Electric/dp/B00005N6L2)

solid title. The first album in the series is legit (see https://github.com/rick/life/issues/7#issuecomment-73267388)

**Comment by rick** [comment]
Thanks for the cookbook tips, @norbert.  :bow:

**Comment by rick** [comment]
> if you like the old jack ryan films and keira knightley i'm here to tell you that the newish jack ryan shadow recruit film is solid

**Comment by rick** [comment]
- [ ] [Wednesday is indigo blue](http://www.amazon.com/Wednesday-Indigo-Blue-Discovering-Synesthesia/dp/0262516705) via @jhosman

**Comment by rick** [comment]
via Les:
- [ ] [Get Low](http://en.wikipedia.org/wiki/Get_Low_%28film%29)
- [ ] [Hot Rod](http://www.imdb.com/title/tt0787475/)

**Comment by rick** [comment]
- [ ] [The Foxcatcher](http://en.wikipedia.org/wiki/Foxcatcher) -- via teyo

**Comment by rick** [comment]
zomg
- [ ] :movie_camera: [What we do in the shadows](http://en.wikipedia.org/wiki/What_We_Do_in_the_Shadows)

**Comment by rick** [comment]
via @rimboy 
- [ ] :movie_camera: [Hobo with a Shotgun](http://en.wikipedia.org/wiki/Hobo_with_a_Shotgun)
- [ ] booker T & the MGs played with CCR at some point...

**Comment by rimboy** [comment]
Time is Tight!
http://somethingelsereviews.com/2015/02/19/booker-t-and-the-mgs-creedence-clearwater-revival/

**Comment by rick** [comment]
Nice!

**Comment by rick** [comment]
- [ ] :book: [Kansas City Lightning](http://www.amazon.com/Kansas-City-Lightning-Charlie-Parker/dp/0062005596)

**Comment by rick** [comment]
- [ ] :book: [The Servile State](http://en.wikipedia.org/wiki/The_Servile_State), see also https://gist.github.com/cwage/a88d7cf21adeb0494837
- [ ] :book: [The Captive Mind](http://en.wikipedia.org/wiki/The_Captive_Mind), "one of the most depressing books I've ever read" -- cwage

**Comment by rick** [comment]
Some more Haruki Murakami stories:
- [ ] http://www.newyorker.com/magazine/2015/02/23/kino
- [ ] http://www.newyorker.com/magazine/2014/10/13/scheherazade-3
- [ ] http://www.newyorker.com/magazine/2014/06/09/yesterday-3

**Comment by rick** [comment]
- [ ] :movie_camera: [Control](http://en.wikipedia.org/wiki/Control_%282007_film%29)

**Comment by rimboy** [comment]
Caught it at the Belcourt. It's good but did not need to be shot in black and white. 

Sean

**Comment by rick** [comment]
- [ ] :books: [Distinction](http://www.amazon.com/Distinction-Social-Critique-Judgement-Taste/dp/0674212770/ref=sr_1_1?s=books&ie=UTF8&qid=1426175679&sr=1-1&keywords=distinction+bourdieu)

**Comment by rick** [comment]
- [ ] :books: [Teach like a champion](http://www.amazon.com/gp/product/1118901851/?tag=wwwwileycom-20)

**Comment by rick** [comment]
- [ ] :cd: [JDilla - Donuts](https://www.rdio.com/artist/J_Dilla/album/Donuts/)

**Comment by rick** [comment]
via: http://priceonomics.com/hiking-the-2650-mile-pacific-crest-trail/
- [ ] :movie_camera: [Only the Essential](http://www.onlytheessential.com/)
- [ ] :book: [Wild: From Lost to Found on the Pacific Crest Trail](http://www.amazon.com/Wild-Found-Pacific-Crest-Trail/dp/0307476073)

**Comment by rick** [comment]
- [ ] :book: [Radical Acceptance: Embracing Your Life With the Heart of a Buddha: Tara Brach: 9780553380996: Amazon.com: Books](http://www.amazon.com/Radical-Acceptance-Embracing-Heart-Buddha/dp/0553380990)

via [some timothy ferris thing on depression / suicide, etc.](http://fourhourworkweek.com/2015/05/06/how-to-commit-suicide/). Comes highly recommended.  No, I'm not researching suicide, dammit.

also, recommended by @cwage:  
- [ ] :book: [Every Cradle Is a Grave: Rethinking the Ethics of Birth and Suicide: Sarah Perry: 9780989697293: Amazon.com: Books](http://www.amazon.com/Every-Cradle-Grave-Rethinking-Suicide/dp/0989697290/)

**Comment by rick** [comment]
:books:
- [x] [Amazon.com: The Path of Individual Liberation: The Profound Treasury of the Ocean of Dharma, Volume One (9781611801040): Chogyam Trungpa, Judith L. Lief: Books](http://www.amazon.com/Path-Individual-Liberation-Profound-Treasury/dp/1611801044/ref=sr_1_3?ie=UTF8&qid=1431587490&sr=8-3&keywords=trungpa+ocean+dharma)
- [x] [Amazon.com: The Bodhisattva Path of Wisdom and Compassion: The Profound Treasury of the Ocean of Dharma, Volume Two (9781611801057): Chogyam Trungpa, Judith L. Lief: Books](http://www.amazon.com/Bodhisattva-Path-Wisdom-Compassion-Profound/dp/1611801052/ref=sr_1_4?ie=UTF8&qid=1431587490&sr=8-4&keywords=trungpa+ocean+dharma)
- [x] [Amazon.com: The Tantric Path of Indestructible Wakefulness: The Profound Treasury of the Ocean of Dharma, Volume Three (9781590308042): Chogyam Trungpa, Judith L. Lief: Books](http://www.amazon.com/Tantric-Path-Indestructible-Wakefulness-Profound/dp/1590308042/ref=sr_1_1?ie=UTF8&qid=1431587490&sr=8-1&keywords=trungpa+ocean+dharma)

**Comment by rick** [comment]
via @vinbarnes 
- [ ] :musical_score: [Jeff Beck - Going Down](https://www.rdio.com/artist/Jeff_Beck/album/Going_Down/)
- [ ] :musical_score: [J Roddy Walston & The Business – Rdio](https://www.rdio.com/artist/J_Roddy_Walston__The_Business/)
- [ ] :book: :mushroom: [The Psychedelic Explorer's Guide: Safe, Therapeutic, and Sacred Journeys: James Fadiman: 9781594774027: Amazon.com: Books](http://www.amazon.com/dp/1594774021/ref=cm_sw_r_awd_kVmqvb08R6SQP)

**Comment by rick** [comment]
:movie_camera: 
- [ ] [Ex Machina (film) - Wikipedia, the free encyclopedia](http://en.wikipedia.org/wiki/Ex_Machina_%28film%29)

**Comment by rick** [comment]
Shit that's recently been out that I could maybe catch up on eventually:
- [x] :tv: Daredevil
- [ ] Avengers Age of Ultron
- [ ] the new Mad Max
- [ ] Ex Machina
- [ ] Furious 7 (no joke)
- [ ] silicon valley, after episode 6 / season 2

**Comment by rimboy** [comment]
I'd be game to check out the Mad Max, a number of friends have been raving
about it.

Sean

**Comment by rick** [comment]
Kinda random: http://www.phares-balises.fr/detail0_uk.php?id=1038

**Comment by rick** [comment]
:movie_camera:  Wilco [Every Other Summer](https://www.google.com/search?q=wilco+every+other+summer&oq=wilco+every+other+s&aqs=chrome.0.0j69i57j69i60.2923j0j7&sourceid=chrome&es_sm=119&ie=UTF-8)  h/t bval

**Comment by rick** [comment]
- [ ] :book: [Aramis, or the Love of Technology](http://www.amazon.com/Aramis-Love-Technology-Bruno-Latour/dp/0674043235/ref=sr_1_1/191-2866695-5999941?ie=UTF8&qid=1435612010&sr=8-1&keywords=aramis+love+technology&pebp=1435612013134&perid=0YA5DKF9HN0Z265VNEX7)

**Comment by rick** [comment]
- [ ] :musical_note: http://www.complex.com/music/2015/07/illfightyou-new-ep-premiere-cashinthebathroom (via leehuffman)
